### ISSUE TITLE
Installation with Dockerfile

### ISSUE THREAD

**Issue by aarist** [k4ntz/OC_Atari#25]
Hey, 
the installation works fine with the provided Dockerfile, however the demos don't work out of the box, because `requirements.txt` installs the newest version of all the packages. This leads to errors, e.g. from open-cv:
`AttributeError: module 'cv2.dnn' has no attribute 'DictValue'`
I can resolve this problem by simply installing an older version of opencv with:
` pip install opencv-python==4.8.0.74`
Thus, I would like to suggest specifying all the package versions in` requirements.txt`.

**Comment by BluemlJ** [comment]
We added specific package versions to the requirements.txt. 
Thanks for the recommendation.
