### ISSUE TITLE
Out of Date PyPi

### ISSUE THREAD

**Issue by PaladinMorak** [k4ntz/OC_Atari#30]
With [this commit](https://github.com/k4ntz/HackAtari/commit/7db6be989c0c6c423c99142e2e901c05c430bb19) of [HackAtari](https://github.com/k4ntz/HackAtari) the [step function](https://github.com/k4ntz/OC_Atari/blob/96411aa46ee5591e2da3290a3dccbe21f47294ea/ocatari/core.py#L197)  is now required, however the last uploaded version of OC_Atari on PyPI was updated in August of this year and as such still raises a `NotImplementedError` when the step function is called.

**Comment by BluemlJ** [comment]
New major release 2.0 is now on pypi
